version: '3.7'
name: gb-laravel
services:
  mysql:
    image: mysql:latest
    hostname: mysql
    container_name: mysql
    ports:
      - "3316:3306"
    volumes:
      - ./data:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345
      TZ: Asia/Yekaterinburg
